version: "3"

services:
  mongodb:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
    container_name: "mongodb_study"
    ports:
      - "27017:27017"