spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

      #postgres=# create database studyolle;
      #postgres=# create user studyollejpa with encrypted password '1234';
      #postgres=# grant all privileges on database studyolle to studyollejpa;
  datasource:
    url: jdbc:postgresql://studyolle-postgres:5432/studyolle
    username: studyollejpa
    password: 1234
    driver-class-name: org.postgresql.Driver
