spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      #postgres=# create database budgetdb;
      #postgres=# create user budget with encrypted password '1234';
      #postgres=# grant all privileges on database budgetdb to budget;
  datasource:
    url: jdbc:postgresql://localhost:5432/budgetdb
    username: budget
    password: 1234
    driver-class-name: org.postgresql.Driver

