version: "3.1"

services:
  redis_container:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - my경로:/data
    restart: always
    command: redis-server /usr/local/conf/redis.conf